### ISSUE TITLE
Data - Create sample packages

### ISSUE THREAD

**Issue by jeffscottward** [polywrap/web3hub#44]

**Comment by jeffscottward** [comment]
Instructions here: 5 should be enough to test with
https://github.com/Web3-API/web3hub/issues/23

**Comment by jeffscottward** [comment]
@leif <- need to add you to this repo somehow cc @dOrgJelli

**Comment by dorglkramer** [comment]
that's @leiforion

**Comment by jeffscottward** [comment]
added @leiforion  let me know if that doesnt work
